// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pamukkale_university/ent/departments"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DepartmentsCreate is the builder for creating a Departments entity.
type DepartmentsCreate struct {
	config
	mutation *DepartmentsMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (dc *DepartmentsCreate) SetCode(s string) *DepartmentsCreate {
	dc.mutation.SetCode(s)
	return dc
}

// SetName sets the "name" field.
func (dc *DepartmentsCreate) SetName(s string) *DepartmentsCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetDegreeType sets the "degree_type" field.
func (dc *DepartmentsCreate) SetDegreeType(b bool) *DepartmentsCreate {
	dc.mutation.SetDegreeType(b)
	return dc
}

// SetNillableDegreeType sets the "degree_type" field if the given value is not nil.
func (dc *DepartmentsCreate) SetNillableDegreeType(b *bool) *DepartmentsCreate {
	if b != nil {
		dc.SetDegreeType(*b)
	}
	return dc
}

// SetQuota sets the "quota" field.
func (dc *DepartmentsCreate) SetQuota(i int) *DepartmentsCreate {
	dc.mutation.SetQuota(i)
	return dc
}

// SetID sets the "id" field.
func (dc *DepartmentsCreate) SetID(u uuid.UUID) *DepartmentsCreate {
	dc.mutation.SetID(u)
	return dc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dc *DepartmentsCreate) SetNillableID(u *uuid.UUID) *DepartmentsCreate {
	if u != nil {
		dc.SetID(*u)
	}
	return dc
}

// Mutation returns the DepartmentsMutation object of the builder.
func (dc *DepartmentsCreate) Mutation() *DepartmentsMutation {
	return dc.mutation
}

// Save creates the Departments in the database.
func (dc *DepartmentsCreate) Save(ctx context.Context) (*Departments, error) {
	dc.defaults()
	return withHooks[*Departments, DepartmentsMutation](ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DepartmentsCreate) SaveX(ctx context.Context) *Departments {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DepartmentsCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DepartmentsCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DepartmentsCreate) defaults() {
	if _, ok := dc.mutation.DegreeType(); !ok {
		v := departments.DefaultDegreeType
		dc.mutation.SetDegreeType(v)
	}
	if _, ok := dc.mutation.ID(); !ok {
		v := departments.DefaultID()
		dc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DepartmentsCreate) check() error {
	if _, ok := dc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Departments.code"`)}
	}
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Departments.name"`)}
	}
	if _, ok := dc.mutation.DegreeType(); !ok {
		return &ValidationError{Name: "degree_type", err: errors.New(`ent: missing required field "Departments.degree_type"`)}
	}
	if _, ok := dc.mutation.Quota(); !ok {
		return &ValidationError{Name: "quota", err: errors.New(`ent: missing required field "Departments.quota"`)}
	}
	return nil
}

func (dc *DepartmentsCreate) sqlSave(ctx context.Context) (*Departments, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DepartmentsCreate) createSpec() (*Departments, *sqlgraph.CreateSpec) {
	var (
		_node = &Departments{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(departments.Table, sqlgraph.NewFieldSpec(departments.FieldID, field.TypeUUID))
	)
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dc.mutation.Code(); ok {
		_spec.SetField(departments.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := dc.mutation.Name(); ok {
		_spec.SetField(departments.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dc.mutation.DegreeType(); ok {
		_spec.SetField(departments.FieldDegreeType, field.TypeBool, value)
		_node.DegreeType = value
	}
	if value, ok := dc.mutation.Quota(); ok {
		_spec.SetField(departments.FieldQuota, field.TypeInt, value)
		_node.Quota = value
	}
	return _node, _spec
}

// DepartmentsCreateBulk is the builder for creating many Departments entities in bulk.
type DepartmentsCreateBulk struct {
	config
	builders []*DepartmentsCreate
}

// Save creates the Departments entities in the database.
func (dcb *DepartmentsCreateBulk) Save(ctx context.Context) ([]*Departments, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Departments, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepartmentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DepartmentsCreateBulk) SaveX(ctx context.Context) []*Departments {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DepartmentsCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DepartmentsCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
