// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pamukkale_university/ent/departments"
	"pamukkale_university/ent/predicate"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDepartments = "Departments"
)

// DepartmentsMutation represents an operation that mutates the Departments nodes in the graph.
type DepartmentsMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	code          *string
	name          *string
	degree_type   *bool
	quota         *int
	addquota      *int
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Departments, error)
	predicates    []predicate.Departments
}

var _ ent.Mutation = (*DepartmentsMutation)(nil)

// departmentsOption allows management of the mutation configuration using functional options.
type departmentsOption func(*DepartmentsMutation)

// newDepartmentsMutation creates new mutation for the Departments entity.
func newDepartmentsMutation(c config, op Op, opts ...departmentsOption) *DepartmentsMutation {
	m := &DepartmentsMutation{
		config:        c,
		op:            op,
		typ:           TypeDepartments,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDepartmentsID sets the ID field of the mutation.
func withDepartmentsID(id uuid.UUID) departmentsOption {
	return func(m *DepartmentsMutation) {
		var (
			err   error
			once  sync.Once
			value *Departments
		)
		m.oldValue = func(ctx context.Context) (*Departments, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Departments.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDepartments sets the old Departments of the mutation.
func withDepartments(node *Departments) departmentsOption {
	return func(m *DepartmentsMutation) {
		m.oldValue = func(context.Context) (*Departments, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DepartmentsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DepartmentsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Departments entities.
func (m *DepartmentsMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DepartmentsMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DepartmentsMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Departments.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCode sets the "code" field.
func (m *DepartmentsMutation) SetCode(s string) {
	m.code = &s
}

// Code returns the value of the "code" field in the mutation.
func (m *DepartmentsMutation) Code() (r string, exists bool) {
	v := m.code
	if v == nil {
		return
	}
	return *v, true
}

// OldCode returns the old "code" field's value of the Departments entity.
// If the Departments object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DepartmentsMutation) OldCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCode: %w", err)
	}
	return oldValue.Code, nil
}

// ResetCode resets all changes to the "code" field.
func (m *DepartmentsMutation) ResetCode() {
	m.code = nil
}

// SetName sets the "name" field.
func (m *DepartmentsMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DepartmentsMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Departments entity.
// If the Departments object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DepartmentsMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *DepartmentsMutation) ResetName() {
	m.name = nil
}

// SetDegreeType sets the "degree_type" field.
func (m *DepartmentsMutation) SetDegreeType(b bool) {
	m.degree_type = &b
}

// DegreeType returns the value of the "degree_type" field in the mutation.
func (m *DepartmentsMutation) DegreeType() (r bool, exists bool) {
	v := m.degree_type
	if v == nil {
		return
	}
	return *v, true
}

// OldDegreeType returns the old "degree_type" field's value of the Departments entity.
// If the Departments object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DepartmentsMutation) OldDegreeType(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDegreeType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDegreeType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDegreeType: %w", err)
	}
	return oldValue.DegreeType, nil
}

// ResetDegreeType resets all changes to the "degree_type" field.
func (m *DepartmentsMutation) ResetDegreeType() {
	m.degree_type = nil
}

// SetQuota sets the "quota" field.
func (m *DepartmentsMutation) SetQuota(i int) {
	m.quota = &i
	m.addquota = nil
}

// Quota returns the value of the "quota" field in the mutation.
func (m *DepartmentsMutation) Quota() (r int, exists bool) {
	v := m.quota
	if v == nil {
		return
	}
	return *v, true
}

// OldQuota returns the old "quota" field's value of the Departments entity.
// If the Departments object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DepartmentsMutation) OldQuota(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuota is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuota requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuota: %w", err)
	}
	return oldValue.Quota, nil
}

// AddQuota adds i to the "quota" field.
func (m *DepartmentsMutation) AddQuota(i int) {
	if m.addquota != nil {
		*m.addquota += i
	} else {
		m.addquota = &i
	}
}

// AddedQuota returns the value that was added to the "quota" field in this mutation.
func (m *DepartmentsMutation) AddedQuota() (r int, exists bool) {
	v := m.addquota
	if v == nil {
		return
	}
	return *v, true
}

// ResetQuota resets all changes to the "quota" field.
func (m *DepartmentsMutation) ResetQuota() {
	m.quota = nil
	m.addquota = nil
}

// Where appends a list predicates to the DepartmentsMutation builder.
func (m *DepartmentsMutation) Where(ps ...predicate.Departments) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DepartmentsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DepartmentsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Departments, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DepartmentsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DepartmentsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Departments).
func (m *DepartmentsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DepartmentsMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.code != nil {
		fields = append(fields, departments.FieldCode)
	}
	if m.name != nil {
		fields = append(fields, departments.FieldName)
	}
	if m.degree_type != nil {
		fields = append(fields, departments.FieldDegreeType)
	}
	if m.quota != nil {
		fields = append(fields, departments.FieldQuota)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DepartmentsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case departments.FieldCode:
		return m.Code()
	case departments.FieldName:
		return m.Name()
	case departments.FieldDegreeType:
		return m.DegreeType()
	case departments.FieldQuota:
		return m.Quota()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DepartmentsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case departments.FieldCode:
		return m.OldCode(ctx)
	case departments.FieldName:
		return m.OldName(ctx)
	case departments.FieldDegreeType:
		return m.OldDegreeType(ctx)
	case departments.FieldQuota:
		return m.OldQuota(ctx)
	}
	return nil, fmt.Errorf("unknown Departments field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DepartmentsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case departments.FieldCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCode(v)
		return nil
	case departments.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case departments.FieldDegreeType:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDegreeType(v)
		return nil
	case departments.FieldQuota:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuota(v)
		return nil
	}
	return fmt.Errorf("unknown Departments field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DepartmentsMutation) AddedFields() []string {
	var fields []string
	if m.addquota != nil {
		fields = append(fields, departments.FieldQuota)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DepartmentsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case departments.FieldQuota:
		return m.AddedQuota()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DepartmentsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case departments.FieldQuota:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddQuota(v)
		return nil
	}
	return fmt.Errorf("unknown Departments numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DepartmentsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DepartmentsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DepartmentsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Departments nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DepartmentsMutation) ResetField(name string) error {
	switch name {
	case departments.FieldCode:
		m.ResetCode()
		return nil
	case departments.FieldName:
		m.ResetName()
		return nil
	case departments.FieldDegreeType:
		m.ResetDegreeType()
		return nil
	case departments.FieldQuota:
		m.ResetQuota()
		return nil
	}
	return fmt.Errorf("unknown Departments field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DepartmentsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DepartmentsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DepartmentsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DepartmentsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DepartmentsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DepartmentsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DepartmentsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Departments unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DepartmentsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Departments edge %s", name)
}
