// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Departments is the predicate function for departments builders.
type Departments func(*sql.Selector)
